apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cakeshop
  namespace: cake

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:794934876309:certificate/b5bc39eb-58eb-45ca-b8a9-b59143a0a33a
spec:
  ingressClassName: alb
  rules:
  - host: grafana.tanushadevops.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cakeshop
            port:
              number: 80
